[package]
name = "prollytree"
description = "A prolly (probabilistic) tree for efficient storage, retrieval, and modification of ordered data."
authors = ["Feng Zhang <f.feng.zhang@gmail.com>"]
version = "0.1.0"
edition = "2021"

license = "Apache-2.0"
documentation = "https://docs.rs/prollytree"
repository = "https://github.com/zhangfengcdt/prollytree.git"
keywords = ["prolly", "tree", "probabilistic", "hash"]
categories = ["data-structures", "cryptography"]

[dependencies]
base64 = { version = "0.22.0", optional = true }
sha2 = "0.10"
tracing = { version = "0.1.37", optional = true }
rand = "0.8.5"

[dev-dependencies]
assert_matches = "1.5.0"
criterion = "0.5.1"
insta = "1.31.0"
paste = "1.0.14"
proptest = "1.2.0"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }

[features]
tracing = ["dep:tracing"]
default = ["digest_base64"]
digest_base64 = ["dep:base64"]
